name: library_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  google_fonts: ^6.2.1 # Fuente Lexend
  http: ^1.2.2
  path_provider: ^2.0.15
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_libraryapp.png" # Cambia esto por la ruta de tu ícono
  adaptive_icon_background: "#ffffff" # Color de fondo para Android
  adaptive_icon_foreground: "assets/icon/icon_libraryapp.png" # Opcional, solo para Android
